CryptsOfBuZak/WebApp/Areas/User/Controllers/GameController.cs
using System.Configuration;
using App.BLL.CryptsOfBuzak;
using App.BLL.DTO;
using App.Contracts.BLL;
using App.BLL.DTO.GroupStatus;
using Base.Extensions;
using Domain;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.IdentityModel.Tokens;
using BattleCharacter = App.BLL.DTO.GroupStatus.BattleCharacter;
using GroupStatus = App.BLL.DTO.GroupStatus.GroupStatus;
using InRaidEffect = App.BLL.DTO.GroupStatus.InRaidEffect;
using JsonSerializer = System.Text.Json.JsonSerializer;

namespace WebApp.Areas.User.Controllers
{
    [Area("User")]
    [Authorize(Roles = "user")]
    public class GameController : Controller
    {
        private readonly IAppBLL _bll;

        public GameController(IAppBLL bll)
        {
            _bll = bll;
        }
        
        // GET
        public async Task<IActionResult> Index()
        {

            // Guid name = _bll.AppUsers.FirstOrDefaultAsync(User.GetUserId()).Result?.CharacterId ?? default;
            bool check = await _bll.Characters.FirstOrDefaultAsync(User.GetUserId()) == null;
            
            if (check)
            {
                return RedirectToAction(nameof(CreateCharacter));
            }

            GroupStatus? gs = await _bll.GroupStatuses.GetByLeaderIdAsync(User.GetUserId());
            if (gs != null)
            {
                if (gs.DungeonZoneNumber != null)
                {
                    return RedirectToAction(nameof(Camp));
                }
            }

            var res = (await _bll.Dungeons.GetAllAsync()).ToList();
            foreach (var dungeon in res)
            {
                var dungeonZones = (await _bll.DungeonZones.GetAllByDungeonIdAsync(dungeon.Id)).ToList();
                dungeon.DungeonZones = dungeonZones;
            }

            return View(res);
        }
        
        // GET: Game/CreateCharacter
        public IActionResult CreateCharacter()
        {
            // bool check = _bll.AppUsers.FirstOrDefault(User.GetUserId())!.CharacterId != default;
            
            bool check = _bll.Characters.FirstOrDefault(User.GetUserId()) != null;
            if (check)
            {
                return RedirectToAction(nameof(Index), new {var = check});
            }
            return View();
        }

        // GET: Game/FormParty
        public async Task<IActionResult> FormParty(int? id)
        {
            Character? character = _bll.Characters.FirstOrDefault(User.GetUserId());
            
            if (character == null)
            {
                return RedirectToAction(nameof(CreateCharacter));
            }
            
            GroupStatus? res = await _bll.GroupStatuses.FirstOrDefaultAsync(User.GetUserId());
            bool createNew = false;
            
            if(res == null)
            {
                // Group Doesn't exist yet, create one.
                res = Core.CreateGroupStatus(character);
                createNew = true;
            }

            if (res.DungeonId == null && id == null)
            {
                // Can't find any dungeon.
                return NotFound();
            }

            // If id is null - get dungeon id from groupStatus
            if(id == null && res.DungeonId != null)
            {
                id = res.DungeonId;
            }
            
            // Check if Dungeon actually exists and if group already exists
            if (await _bll.Dungeons.FirstOrDefaultAsync(id!.Value) == null || res.DungeonZoneNumber != null)
            {
                return RedirectToAction(nameof(Index));
            }
            
            res.DungeonId = id;

            if (createNew)
            {
                _bll.GroupStatuses.Add(res);
            }
            else
            {
                _bll.GroupStatuses.Update(res);
            }
            
            await _bll.SaveChangesAsync();
            
            character.FriendList = (await _bll.Friends.GetAllByIdAsync(character.Id)).ToList();
            res.Dungeon = await _bll.Dungeons.FirstOrDefaultAsync(id.Value);
            res.Dungeon!.DungeonZones = (await _bll.DungeonZones.GetAllByDungeonIdAsync(id.Value)).ToList();
            res.GroupLeader = character;

            return View(res);
        }

        [HttpPost, ActionName("InviteToParty")]
        public async Task<IActionResult> PartyInvite(Guid id)
        {
            GroupStatus? gs = _bll.GroupStatuses.FirstOrDefault(User.GetUserId());
            // if BattleCharacters aren't null - adventure already in progress.
            //TODO! Check DungeonZoneNumber instead of BattleCharacters.
            if (gs?.BattleCharacters == null)
            {
                return RedirectToAction(nameof(Index));
            }

            if (gs.BattleCharacters!.Count > 0)
            {
                return RedirectToAction(nameof(Index));
            }

            List<Guid> guidList = new List<Guid>();
            
            if (gs.GameHistory != "")
            {
                guidList = JsonSerializer.Deserialize<List<Guid>>(gs.GameHistory)!;
            }
            if (guidList.Contains(id) || guidList.Count > 3)
            {
                //Such friend already exists in party! || Party is already full, maximum 3 friends!
                return RedirectToAction(nameof(FormParty));
            }

            // Checks whether a character with such guid in your friendList.
            Character? friendCharacter = (await _bll.Friends.GetAllByIdAsync(User.GetUserId())).ToList()
                .FirstOrDefault(x => x.FriendId == id)?.FriendCharacter;

            if (friendCharacter == null)
            {
                //Friend with such Id is not your friend or doesn't exist!
                return RedirectToAction(nameof(FormParty));
            }
            
            // Good ending.
            guidList.Add(friendCharacter.Id);
            gs.GameHistory = JsonSerializer.Serialize(guidList);
            _bll.GroupStatuses.Update(gs);
            await _bll.SaveChangesAsync();
            
            return RedirectToAction(nameof(FormParty));
        }
        
        [HttpPost, ActionName("RemoveFromParty")]
        public async Task<IActionResult> PartyRemove(Guid id)
        {
            var groupStatus = await _bll.GroupStatuses.FirstOrDefaultAsync(User.GetUserId());
            if (groupStatus == null)
            {
                return RedirectToAction(nameof(Index));
            }
            //Checks that groupstatus have BattleCharacters and GameHistory
            if (groupStatus.BattleCharacters == null || string.IsNullOrEmpty(groupStatus.GameHistory))
            {
                return RedirectToAction(nameof(FormParty));
            }

            List<Guid> guidList = JsonSerializer.Deserialize<List<Guid>>(groupStatus.GameHistory)!;
            
            if (guidList.All(x => x != id))
            {
                //Character with such id doesn't exist in your party!
                return RedirectToAction(nameof(FormParty));
            }

            guidList.Remove(id);
            groupStatus.GameHistory = JsonSerializer.Serialize(guidList);
            _bll.GroupStatuses.Update(groupStatus);
            await _bll.SaveChangesAsync();

            return RedirectToAction(nameof(FormParty));
        }

        // Properly Assign dungeon to GroupStatus. Confirms that Adventure has started.
        [HttpPost, ActionName("StartAdventure")]
        public async Task<IActionResult> StartParty(int? id)
        {
            //TODO!!! Check Dungeon and DungeonZone from Groupstatus. If not null - redirect to Camp or Index?
            GroupStatus? groupstatus = await _bll.GroupStatuses.FirstOrDefaultAsync(User.GetUserId());
            
            if (groupstatus == null)
            {
                //Group doesn't exist!
                return RedirectToAction(nameof(Index));
            }
            
            if (id == null && groupstatus.DungeonId != null)
            {
                id = groupstatus.DungeonId.Value;
            }
            else if (id == null)
            {
                return RedirectToAction(nameof(Index));
            }

            Dungeon? dungeon = await _bll.Dungeons.FirstOrDefaultByIdAsync(id.Value);

            if (dungeon?.DungeonZones == null)
            {
                return RedirectToAction(nameof(Index));
            }
            
            List<Guid> guidList = new List<Guid>();
            
            if (!groupstatus.GameHistory.IsNullOrEmpty())
            {
                guidList = JsonSerializer.Deserialize<List<Guid>>(groupstatus.GameHistory) ?? new List<Guid>();
            }
            
            groupstatus.BattleCharacters = new List<BattleCharacter>();
            
            // Create leader's battleCharacter.
            Character character = (await _bll.Characters.FirstOrDefaultAsync(User.GetUserId()))!;
            BattleCharacter leader =
                Core.CreateBattleCharacter(character);
            leader.GroupStatusId = groupstatus.Id;
            
            _bll.BattleCharacters.Add(leader);
            
            groupstatus.BattleCharacters.Add(leader);
            groupstatus.BattleCharacterLeaderId = leader.Id;
            groupstatus.DungeonId = id;
            
            // Create leader's teammates battleCharacters .
            foreach (var friend in (await _bll.Friends.GetAllByIdAsync(User.GetUserId())).ToList())
            {
                Character? friendCharacter = friend.FriendCharacter;
                if (friendCharacter != null && guidList.Exists(x => x == friend.FriendId))
                {
                    // pay friends for hiring. tax is 50%.
                    friendCharacter.Money += (friendCharacter.Level * 5);
                    character.Money -= (friendCharacter.Level * 10);
                    
                    BattleCharacter bc = Core.CreateBattleCharacter(friendCharacter);

CryptsOfBuZak/WebApp/Areas/User/Controllers/MyCharacterController.cs
using App.Contracts.BLL;
using Base.Extensions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace WebApp.Areas.User.Controllers;

[Area("User")]
[Authorize(Roles = "user")]
public class MyCharacterController : Controller
{
    private readonly IAppBLL _bll;
    
    public MyCharacterController(IAppBLL bll)
    {
        _bll = bll;
    }
    
    
    // GET
    public async Task<IActionResult> Index()
    {
        var res = await _bll.Characters.FirstOrDefaultSensitiveAsync(User.GetUserId());
        
        if (res == null)
        {
            return RedirectToAction("CreateCharacter", "Game");
        }
        
        return View(res);
    }
    
    // GET
    [HttpGet]
    public async Task<IActionResult> ChangeName()
    {
        var res = await _bll.Characters.FirstOrDefaultAsync(User.GetUserId());

        if (res == null)
        {
            return NotFound();
        }
        
        return View(res);
    }
    
    // POST
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> ChangeName(string name)
    {
        var character = (await _bll.Characters.FirstOrDefaultAsync(User.GetUserId()));

        if (character == null)
        {
            return NotFound();
        }
        
        character.Name = name;
        _bll.Characters.Update(character);
        await _bll.SaveChangesAsync();
        
        return RedirectToAction("Index");
    }
}

CryptsOfBuZak/WebApp/Areas/User/Views/Game/CreateCharacter.cshtml
@using Base.Extensions
@using WebApp.Areas.User.Controllers
@model App.BLL.DTO.Character

@{
    ViewData["Title"] = "Create";
}

<h1>Create your character</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CreateCharacter">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CryptsOfBuZak/WebApp/Areas/User/Views/Game/FormParty.cshtml
@using App.BLL.DTO
@using Microsoft.IdentityModel.Tokens
@using JsonSerializer = System.Text.Json.JsonSerializer
@model App.BLL.DTO.GroupStatus.GroupStatus

@{
    Character leader = Model?.GroupLeader ?? throw new InvalidOperationException("LEADER IS NULL!");
    List<Guid> friendGuidList;
    
    if (!String.IsNullOrEmpty(Model.GameHistory))
    {
        friendGuidList = JsonSerializer.Deserialize<List<Guid>>(Model.GameHistory) ?? new List<Guid>();
    }
    else
    {
        friendGuidList = new List<Guid>();
    }

    int totalcost = 0;

    if (!friendGuidList.IsNullOrEmpty())
    {
        List<Friend> friends= Model.GroupLeader.FriendList!.Where(x => friendGuidList.Exists(y => y == x.FriendId)).ToList();
        foreach (var frend in friends)
        {
            if (frend.FriendCharacter != null)
            {
                totalcost += frend.FriendCharacter.Level * 10;
            }
        }
    }

    
}

@if (Model.Dungeon != null)
{
    <h2>Form Party</h2>
}
else
{
    throw new NullReferenceException("Dungeon doesn't exist!");
}

<div class="container">
    <div class="row">
        <div class="col-5 p-3 mb-2 bg-secondary bg-opacity-10 rounded">
            <div class="pt-2">
                <b>@Model.Dungeon.Name</b>
            </div>
            <div class="pt-1">
            Average level: @Model.Dungeon.AverageLevel
            </div>
            <div class="pt-1">
                Zones: @Model.Dungeon.DungeonZones?.Count
            </div>
            <div class="pt-3">
            @Model.Dungeon.Description
            </div>
        </div>
        <div class="col-7">
            <div class="p-3 mb-2 bg-secondary bg-opacity-10 rounded">
                <h5>
                    Party
                </h5>
                <table width="100%">
                    <tr>
                        <td width="60%">
                            @(leader.Name)(@leader.Level lvl)
                        </td>
                        <td align="right">
                            <form asp-action="StartAdventure">
                                <input type="hidden" name="id" value="@Model.DungeonId"/>
                                <input type="submit" value="Start Adventure!" class="btn btn-primary"/>
                            </form>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            Money: @(leader.Money)d
                        </td>
                        <td align="right">
                            Cost to start: @(totalcost)d
                        </td>
                    </tr>

                    <tr>
                        <td>---Members(@(friendGuidList.Count + 1)/4)---------</td><td></td>
                    </tr>

                    @if (Model!.GameHistory != "")
                    {
                        @foreach (Friend partyMember in Model?.GroupLeader?.FriendList!)
                        {
                            if (friendGuidList.Exists(x => x == partyMember.FriendId))
                            {
                                <tr>
                                    <td>
                                        •@partyMember.FriendCharacter?.Name (@(partyMember.FriendCharacter?.Level) lvl) | @(partyMember.FriendCharacter?.Level * 10) denga
                                    </td>
                                    <td align="right">
                                        <form asp-action="RemoveFromParty">
                                            <input type="hidden" name="id" value="@partyMember.FriendId"/>
                                            <input type="submit" value="Remove From Party" class="btn btn-danger"/>
                                        </form>
                                    </td>
                                </tr>
                            }
                        }
                    }

                </table>
            </div>

            <div class="p-3 mb-2 bg-secondary bg-opacity-10 rounded-3">
                <h5>Friends</h5>
                <table width="100%">
                    @if (Model?.GroupLeader?.FriendList != null)
                    {
                        @foreach (Friend friend in Model?.GroupLeader?.FriendList!)
                        {
                            if (!friendGuidList.Exists(x => x == friend.FriendId))
                            {
                                <tr>
                                    <td width="60%">
                                        •@friend.FriendCharacter!.Name (@(friend.FriendCharacter.Level) lvl)
                                    </td>
                                    <td align="right">
                                        @if (Model.GroupLeader.Money >= totalcost + friend.FriendCharacter.Level * 10 && friendGuidList.Count < 3)
                                        {
                                            <form asp-action="InviteToParty">
                                                <input type="hidden" name="id" value="@friend.FriendId"/>
                                                <input type="submit" value="Hire for @(friend.FriendCharacter.Level * 10) denga" class="btn btn-secondary"/>
                                                @* Make unpressable if not enough money (grey) *@
                                            </form>
                                        }
                                        else
                                        {
                                            <input type="button" value="Hire for @(friend.FriendCharacter.Level * 10) denga" class="btn btn-outline-secondary disabled"/>
                                        }
                                    </td>
                                </tr>
                            }
                        }
                    }
                </table>
            </div>
        </div>
    </div>
</div>

CryptsOfBuZak/WebApp/Areas/User/Views/Game/Index.cshtml
@model IEnumerable<App.BLL.DTO.Dungeon>
@{
    ViewData["Title"] = "Index";
}

<h1>YOUR CHARACTER HERE <a asp-controller="MyCharacter">CLICK</a></h1>

<h2>CHOOSE Y'ORE DUNGEON</h2>
<div class="container">
    <div class="col-8 p-3 mb-2 bg-secondary bg-opacity-10 rounded">
        <table class="table table-striped align-middle id-dungeons">
            @foreach (var dungeon in Model!)
            {
                <tr>
                    <td>
                        @dungeon.Name
                    </td>
                    <td>
                        Average level: @dungeon.AverageLevel

                    </td>
                    <td>
                        Zones:
                        @if (dungeon.DungeonZones != null)
                        {
                            @dungeon.DungeonZones.Count.ToString()
                        }
                    </td>
                    <td>
                        <form asp-action="FormParty">
                            <input type="hidden" name="id" value="@dungeon.Id"/>
                            <input type="submit" value="Form Group" class="btn btn-primary"/>
                        </form>
                    </td>
                </tr>
            }
        </table>
    </div>
</div>