CryptsOfBuZak/WebApp/Areas/User/Controllers/DescriptionController.cs
using App.BLL.DTO;
using App.Contracts.BLL;
using Domain;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace WebApp.Areas.User.Controllers;

[Area("User")]
[Authorize(Roles = "user")]

public class DescriptionController : Controller
{
    private readonly IAppBLL _bll;
    
    public DescriptionController(IAppBLL bll)
    {
        _bll = bll;
    }

    public async Task<IActionResult> ItemDescription(int id)
    {
        Item? item = await _bll.Items.FirstOrDefaultAsync(id);
        if (item == null)
        {
            return NotFound();
        }
        
        if( (item.Category == EItemCategory.Artifact || item.Category == EItemCategory.Consumable) && item.EffectId != null )
        {
            Effect? effect = await _bll.Effects.FirstOrDefaultAsync(item.EffectId.Value);
            if (effect != null)
            {
                item.Effect = effect;
            }
            
        }
        else if (item.Category == EItemCategory.SkillBook && item.SkillId != null)
        {
            Skill? skill = await _bll.Skills.FirstOrDefaultAsync(item.SkillId.Value);
            if (skill != null)
            {
                item.Skill = skill;
            }
        }
        return View(item);
    }
    
    public async Task<IActionResult> EffectDescription(int id)
    {
        Effect? effect = await _bll.Effects.FirstOrDefaultAsync(id);
        if (effect == null)
        {
            return NotFound();
        }
        return View(effect);
    }
    
    public async Task<IActionResult> SkillDescription(int id)
    {
        Skill? skill = await _bll.Skills.FirstOrDefaultAsync(id);
        if (skill == null)
        {
            return NotFound();
        }

        Effect? effect = await _bll.Effects.FirstOrDefaultAsync(skill.EffectId);
        if (effect != null)
        {
            skill.Effect = effect;
        }
        else
        {
            return BadRequest();
        }
        return View(skill);
    }
}

CryptsOfBuZak/WebApp/Areas/User/Controllers/ShopController.cs
using App.BLL.CryptsOfBuzak;
using App.BLL.DTO;
using App.Contracts.BLL;
using Base.Extensions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace WebApp.Areas.User.Controllers;

[Area("User")]
[Authorize(Roles = "user")]
public class ShopController : Controller
{
    
    private readonly IAppBLL _bll;

    public ShopController(IAppBLL bll)
    {
        _bll = bll;
    }
    
    //GET
    public async Task<IActionResult> Index()
    {
        Character? character = _bll.Characters.FirstOrDefault(User.GetUserId());
        
        if (character == null)
        {
            return NotFound();
        }
        
        character.InventoryItems = (await _bll.InventoryItems.GetAllByCharacterIdAsync(character.Id)).ToList();

        List<Item> itemList = (await _bll.Items.GetAllAvailableByLevel(character.Level)).ToList();

        ViewData["BuyList"] = itemList;
        
        return View(character);
    }
    
    [HttpPost]
    public async Task<IActionResult> Index(int itemId, int amount, bool sell)
    {
        // throw new NotImplementedException();


        Character? character = await _bll.Characters.FirstOrDefaultAsync(User.GetUserId());

        if (character == null)
        {
            return NotFound();
        }

        if (sell)
        {
            InventoryItem? item = await _bll.InventoryItems.FirstOrDefaultAsync(User.GetUserId(), itemId);
            
            if (item == null)
            {
                ViewData["ErrorMessage"] = "Item not found!";
            }
            else if (item.Item == null)
            {
                ViewData["ErrorMessage"] = "Item references null, not found!";
            }
            else if (item.CharacterId != User.GetUserId())
            {
                ViewData["ErrorMessage"] = "You don't own this item!";
            }
            else if (amount < 1)
            {
                ViewData["ErrorMessage"] = "You can't sell negative or zero items! Seriously, how you gonna do this?";
            }
            else if (item.Amount < amount)
            {
                ViewData["ErrorMessage"] = "You trying to sell more than you have!";
            }
            else
            {
                if (item.Amount - amount > 0)
                {
                    item.Amount -= amount;
                    character.Money += item.Item.Price * amount;
                
                    item.Item = null;
                    _bll.InventoryItems.Update(item);

                }
                else
                {
                    await _bll.InventoryItems.RemoveAsync(User.GetUserId(), itemId);
                    character.Money += item.Item.Price * amount;
                }

                _bll.Characters.Update(character);
                await _bll.SaveChangesAsync();
            }
        }
        else
        {
            Item? item = await _bll.Items.FirstOrDefaultAsync(itemId);

            if (item == null)
            {
                ViewData["ErrorMessage"] = "Item not found!";
            }
            else if (amount <= 0)
            {
                ViewData["ErrorMessage"] = "You can't buy negative or zero items! Seriously, how you gonna do this?";
            }
            else if (item.Price * amount > character.Money)
            {
                ViewData["ErrorMessage"] = "You can't afford this, you don't have enough money!";
            }
            else if (item.MinLevelToBuy == null || character.Level < item.MinLevelToBuy)
            {
                ViewData["ErrorMessage"] = "You can't buy this!";
            }
            else
            {
                ViewData["ErrorMessage"] = $"You successfully bought {amount} {item.Name}! Current Balance: {character.Money}denga";
                ViewData["Test"] = character;
            
                character.Money -= item.Price * amount;
                _bll.Characters.Update(character);
            
                InventoryItem? inventoryItem = 
                    await _bll.InventoryItems.FirstOrDefaultAsync(User.GetUserId(), itemId);

                if (inventoryItem == null)
                {
                    inventoryItem = Core.CreateInventoryItem(User.GetUserId(), itemId, amount);
                }
                else
                {
                    inventoryItem.Amount += amount;
                    inventoryItem.Item = null;
                }
            
                _bll.InventoryItems.Update(inventoryItem);
                await _bll.SaveChangesAsync();
            }
        }
        
        List<Item> itemList = (await _bll.Items.GetAllAvailableByLevel(character.Level)).ToList();

        ViewData["BuyList"] = itemList;
        
        character.InventoryItems = (await _bll.InventoryItems.GetAllByCharacterIdAsync(character.Id)).ToList();

        return View(character);
    }
}

CryptsOfBuZak/WebApp/Areas/User/Views/Shop/Index.cshtml
@using App.BLL.DTO
@model App.BLL.DTO.Character

@{
    List<Item> buyList; 
    
    if (ViewData["BuyList"] != null)
    {
        buyList = (List<Item>) ViewData["BuyList"]!;
    }
    else
    {
        buyList = new List<Item>();
    }
    
}

<div class="container">
    <div class="row">
        <div class="p-3 mb-2 col-12 bg-secondary text-white rounded">
            <div class="row">
                <div class="col">
                    <div class="row">
                        <div class="col">
                            <div>
                                <h2>Shop</h2>
                            </div>
                            <div>
                                @if (ViewData["ErrorMessage"] != null)
                                {
                                    @ViewData["ErrorMessage"]
                                }
                            </div>
                        </div>
                        <div class="col">
                            <h3>Balance: @Model!.Money</h3>
                        </div>
                    </div>
                    
                </div>
            </div>
        </div>

        <div class="col p-3 me-1 mb-2 bg-secondary bg-opacity-10 rounded">
            <div>
                Items for sale:
                <table class="table table-striped table-bordered border-dark align-middle">
                    @if (buyList.Count > 0)
                    {
                        <tr>
                            <td>Name</td><td>Category</td><td>Price per unit</td><td></td>
                        </tr>
                        @foreach (var item in buyList)
                        {
                            <tr>
                                <td>
                                    <a class="p-0 nav-link text-dark text-decoration-underline"
                                       asp-area="User"
                                       asp-controller="Description"
                                       asp-action="ItemDescription"
                                       asp-route-id="@(item.Id)">
                                        @(item.Name)
                                    </a>
                                </td>
                                <td>
                                    @item.Category
                                </td>
                                <td>
                                    @(item.Price)d
                                </td>
                                <form asp-action="Index">
                                    <td>
                                        <input type="number" name="amount" min="0" size="4"/>
                                    
                                        <input type="hidden" name="itemId" value="@item.Id"/>
                                        <input type="hidden" name="sell" value="false"/>
                                        <input type="submit" value="Buy" class="btn btn-primary"/>
                                    </td>
                                </form>
                            </tr>

                        }
                    }
                    else
                    {
                        <tr>
                            <td>Nothing for sale yet...</td>
                        </tr>
                    }
                </table>
            </div>
        </div>
        <div class="col p-3 ms-1 mb-2 bg-secondary bg-opacity-10 rounded">
            <div>
                Inventory:
                <table class="table table-striped table-bordered border-dark align-middle">
                    @if (Model!.InventoryItems != null)
                    {
                        <tr>
                            <td>Name</td><td>Amount</td><td>Price per unit</td><td></td>
                        </tr>
                        @foreach (InventoryItem invItem in Model.InventoryItems)
                        {
                            if (invItem.Item != null)
                            {
                                <form asp-action="Index">
                                    <tr>
                                        <td>
                                            <a class="nav-link text-dark text-decoration-underline"
                                               asp-area="User"
                                               asp-controller="Description"
                                               asp-action="ItemDescription"
                                               asp-route-id="@(invItem.Item.Id)">
                                                @(invItem.Item.Name)
                                            </a>
                                        </td>
                                        <td>
                                            x@(invItem.Amount)
                                        </td>
                                        <td>
                                            @(invItem.Item.Price)d
                                        </td>
                                        <td>
                                            <input type="number" name="amount" min="0" max="@invItem.Amount" size="3"/>

                                            <input type="hidden" name="itemId" value="@invItem.ItemId"/>
                                            <input type="hidden" name="sell" value="true"/>
                                            <input type="submit" value="Sell" class="btn btn-primary"/>
                                        </td>
                                    </tr>
                                </form>
                            }
                        }
                    }
                    else
                    {
                        <tr>
                            <td>Empty...</td>
                        </tr>
                    }
                </table>
            </div>
        </div>
    </div>
</div>